Portfel/Portfel.App/Models/SzczegolyPortfela.cs
using Portfel.App.Controllers;
using Portfel.Data.Data;

namespace Portfel.App.Models
{
    public class SzczegolyPortfela
    {
        public SzczegolyPortfela(int idPortfela, string nazwaPortfela, IEnumerable<PozycjaSzczegoly> szczegolyPozycji)
        {
            IdPortfela = idPortfela;
            NazwaPortfela = nazwaPortfela;
            Pozycje = szczegolyPozycji;
        }

        public int IdPortfela { get; set; }
        public string NazwaPortfela { get; set; }
        public IEnumerable<PozycjaSzczegoly> Pozycje { get; set; }

    }
}

Portfel/Portfel.App/Controllers/PortfelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Portfel.App.Models;
using Portfel.Data;
using Portfel.Data.Data;
using Portfel.Data.Serwisy;

namespace Portfel.App.Controllers
{
    public class PortfelController : Controller
    {
        private readonly PortfelContext _context;
        private readonly IPortfelSerwis _portfelSerwis;

        public PortfelController(PortfelContext context, IPortfelSerwis portfelSerwis)
        {
            _context = context; // tu inicjalizujemy baze danych
            _portfelSerwis = portfelSerwis;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> MojePortfele()
        {
            var user = HttpContext.User.Identity;
            var uzytkownik = _context.Uzytkownik.FirstOrDefault(x => x.Email == user.Name);

            var portfele = _context.Portfele
                .Include(p => p.Uzytkownik)
                .Include(p => p.KontoGotowkowe)
                .Where(p => p.UzytkownikId == uzytkownik.Id && p.Aktywna == true).ToList();

            return View("MojePortfele", portfele);
        }

        public IActionResult DodajPortfel()
        {
            ViewData["UzytkownikId"] = new SelectList(_context.Uzytkownik, "Id", "Email");
            return View("DodajPortfel");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DodajPortfel([Bind("Nazwa")] StworzPortfelRequest stworzPortfel)
        {
            var user = HttpContext.User.Identity;
            var uzytkownik = _context.Uzytkownik.FirstOrDefault(x => x.Email == user.Name);

            var nazwaNowegoPortfela =
                _context.Portfele.FirstOrDefault(p => p.Nazwa == stworzPortfel.Nazwa && p.Uzytkownik.Email == uzytkownik.Email);

            if (nazwaNowegoPortfela == null)
            {
                if (ModelState.IsValid)
                {
                    var portfel = _context.Portfele.Add(new Data.Data.Portfel()
                    {
                        Nazwa = stworzPortfel.Nazwa,
                        UzytkownikId = uzytkownik.Id,
                        Waluta = "usd"
                    });
                    _context.KontaGotowkowe.Add(new KontoGotowkowe() { Portfel = portfel.Entity });
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(MojePortfele));
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Podaj inną nazwę portfela, taka już istnieje.";
                return View("DodajPortfel");
            }
            ViewData["UzytkownikId"] = new SelectList(_context.Uzytkownik, "Id", "Email", uzytkownik.Id);
            return View("MojePortfele");
        }

        public IActionResult WplacKwote()
        {
            ViewData["UzytkownikId"] = new SelectList(_context.Uzytkownik, "Id", "Email");
            return View("WplacKwote");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult WplacKwote([FromRoute] int id, [Bind("Kwota")] WplataNaPortfelRequest wplata)
        {
            var user = HttpContext.User.Identity;
            var uzytkownik = _context.Uzytkownik.FirstOrDefault(x => x.Email == user.Name);

            if (ModelState.IsValid)
            {
                var kwota = Convert.ToDecimal(wplata.Kwota, Thread.CurrentThread.CurrentCulture);
                _portfelSerwis.WplacSrodkiNaKonto(kwota, id);

                return RedirectToAction(nameof(MojePortfele));
            }
            ViewData["UzytkownikId"] = new SelectList(_context.Uzytkownik, "Id", "Email", uzytkownik.Id);
            return View("MojePortfele");
        }
        public IActionResult WyplacKwote()
        {
            ViewData["UzytkownikId"] = new SelectList(_context.Uzytkownik, "Id", "Email");
            return View("WyplacKwote");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult WyplacKwote([FromRoute] int id, [Bind("Kwota")] WyplataZPortfelaRequest wyplata)
        {
            var user = HttpContext.User.Identity;
            var uzytkownik = _context.Uzytkownik.FirstOrDefault(x => x.Email == user.Name);
            if (ModelState.IsValid)
            {
                var kwota = Convert.ToDecimal(wyplata.Kwota, Thread.CurrentThread.CurrentCulture);
                _portfelSerwis.WyplacSrodkiZKonta(kwota, id);

                return RedirectToAction(nameof(MojePortfele));
            }
            ViewData["UzytkownikId"] = new SelectList(_context.Uzytkownik, "Id", "Email", uzytkownik.Id);
            return View("MojePortfele");
        }
        public IActionResult KupAktywo()
        {
            ViewData["AktywoId"] = new SelectList(_context.Aktywa, "Id", "Nazwa");
            return View("KupAktywo");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> KupAktywo(int id, [Bind("AktywoId, Cena, Ilosc, Komentarz")] KupAktywoRequest kupAktywo)
        {
            var user = HttpContext.User.Identity;
            var uzytkownik = await _context.Uzytkownik.FirstOrDefaultAsync(x => x.Email == user.Name);
            var portfel = await _context.Portfele.FindAsync(id);
            var aktywoSymbol = _context.Aktywa.FirstOrDefault(a => a.Id == kupAktywo.AktywoId).Symbol;
            var cena = Convert.ToDecimal(kupAktywo.Cena, Thread.CurrentThread.CurrentCulture);

            if (ModelState.IsValid)
            {
                _portfelSerwis.KupAktywo(aktywoSymbol, kupAktywo.Ilosc, cena, id, kupAktywo.Komentarz);
                return RedirectToAction(nameof(MojePortfele));
            }
            ViewData["UzytkownikId"] = new SelectList(_context.Uzytkownik, "Id", "Email", uzytkownik.Id);
            return View("MojePortfele");
        }
        public IActionResult SprzedajAktywo()
        {
            ViewData["AktywoId"] = new SelectList(_context.Aktywa, "Id", "Nazwa");
            return View("SprzedajAktywo");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SprzedajAktywo(int id, [Bind("AktywoId, Cena, Ilosc, Komentarz")] SprzedajAktywoRequest sprzedajAktywo)
        {
            var user = HttpContext.User.Identity;
            var uzytkownik = await _context.Uzytkownik.FirstOrDefaultAsync(x => x.Email == user.Name);
            var portfel = await _context.Portfele.FindAsync(id);
            var aktywoSymbol = _context.Aktywa.FirstOrDefault(a => a.Id == sprzedajAktywo.AktywoId).Symbol;

            var cena = Convert.ToDecimal(sprzedajAktywo.Cena, Thread.CurrentThread.CurrentCulture);
            if (ModelState.IsValid)
            {
                _portfelSerwis.SprzedajAktywo(aktywoSymbol, sprzedajAktywo.Ilosc,  cena, id, sprzedajAktywo.Komentarz);
                return RedirectToAction(nameof(MojePortfele));
            }
            ViewData["UzytkownikId"] = new SelectList(_context.Uzytkownik, "Id", "Email", uzytkownik.Id);
            return View("MojePortfele");
        }
        public async Task<IActionResult> SzczegolyPortfela(int id)
        {
            var user = HttpContext.User.Identity;
            if (user.Name == null)
            {
                return View("~/Views/Uzytkownik/StronaLogowania.cshtml");
            }
            var uzytkownik = _context.Uzytkownik.FirstOrDefault(x => x.Email == user.Name);
            var portfel = _context.Portfele
                .Include(p => p.Pozycje)
                .ThenInclude(p => p.Aktywo)
                .FirstOrDefault(p => p.Id == id);
            var aktywa = _context.Aktywa.ToList();

            var szczegolyPozycji = portfel.Pozycje.Select(p => new PozycjaSzczegoly
            {
                Ilosc = p.Ilosc,
                SredniaCenaZakupu = p.SredniaCenaZakupu,
                NazwaAktywa = p.Aktywo.Nazwa,
                WartoscAktywa = p.Aktywo.CenaAktualna
            });
            return View("SzczegolyPortfela", new SzczegolyPortfela(id, portfel.Nazwa, szczegolyPozycji) { });
        }


        public async Task<IActionResult> WszytskieTransakcjeDlaPortfela(int id)
        {
            var user = HttpContext.User.Identity;
            if (user.Name == null)
            {
                return View("~/Views/Uzytkownik/StronaLogowania.cshtml");
            }
            var uzytkownik = _context.Uzytkownik.FirstOrDefault(x => x.Email == user.Name);

            var portfel = _context.Portfele.Include(p => p.Pozycje)
                .ThenInclude(p => p.Aktywo)
                .Include(p=>p.Transakcje)
                .Include(p => p.KontoGotowkowe)
                .ThenInclude(p => p.OperacjeGotowkowe)
                .FirstOrDefault(p => p.Id == id);
            
            return View("WszystkieTransakcje", new WszystkieTransakcjeDlaPortfela(id, portfel.Nazwa, portfel.Transakcje, portfel.KontoGotowkowe.Id, portfel.KontoGotowkowe.OperacjeGotowkowe) { });
        }
    }
    public class PozycjaSzczegoly
    {
        public string NazwaAktywa { get; set; }
        public decimal SredniaWartoscPozycji
        {
            get { return Ilosc * SredniaCenaZakupu; }
        }
        public decimal WartoscPozycji
        {
            get { return Ilosc * WartoscAktywa; }
        }
        public uint Ilosc { get; set; }
        public decimal SredniaCenaZakupu { get; set; }
        public  decimal WartoscAktywa { get; set; }
        public decimal ZyskStrata
        {
            get
            {
                return ((WartoscAktywa * 100) / SredniaCenaZakupu) - 100;
            }
        }
    }
}

Portfel/Portfel.App/Views/Portfel/DodajPortfel.cshtml
@model Portfel.Data.Data.Portfel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="about" class="about" style="margin-bottom: 55px;">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h2>Dodaj nowy portfel</h2>
        </div>
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;  border-color: white;
                                     box-shadow: 0px 2px 25px rgb(0 0 0 / 10%);">
                        <div class="card-body p-5">
                            <div class="info-item d-flex">
                            </div><!-- End Info Item -->
                            <form asp-action="DodajPortfel">
                                <div class="form mb-4">
                                    <label asp-for="Nazwa"></label>
                                    <input asp-for="Nazwa" id="form3Example1cg" class="form-control form-control-lg" />
                                    <span asp-validation-for="Nazwa"></span>
                                </div>
                                <p id="portfelIstnieje" style="color: red">@ViewBag.ErrorMessage</p>
                                <div class="d-flex justify-content-center">
                                    <input id="dodajPortfel" type="submit" value="Dodaj portfel" style="background: var(--color-primary); border: 0; padding: 14px 45px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Portfel/Portfel.App/Views/Portfel/KupAktywo.cshtml
@model Portfel.Data.Data.KupAktywoRequest
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="about" class="about" style="margin-bottom: 55px;">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h2>Kup aktywo</h2>
        </div>
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;  border-color: white;
                                     box-shadow: 0px 2px 25px rgb(0 0 0 / 10%);">
                        <div class="card-body p-5">
                            <div class="info-item d-flex">
                            </div>
                            <form asp-action="KupAktywo" asp-controller="Portfel">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="PortfelId" />
                                <div class="form mb-4">
                                    <label asp-for="AktywoId">Aktywo</label>
                                    <select asp-for="AktywoId" class="form-control form-control-lg" asp-items="ViewBag.AktywoId"></select>
                                </div>
                                <div class="form mb-4">
                                    <label asp-for="Cena" class="control-label"></label>
                                    <input asp-for="Cena" id="form3Example1cg" class="form-control form-control-lg" />
                                    <span asp-validation-for="Cena" class="text-danger"></span>
                                </div>
                                <div class="form mb-4">
                                    <label asp-for="Ilosc" class="control-label">Ilość</label>
                                    <input asp-for="Ilosc" id="form3Example1cg" class="form-control form-control-lg" />
                                    <span asp-validation-for="Ilosc" class="text-danger"></span>
                                </div>
                                <div class="form mb-4">
                                    <label asp-for="Komentarz" class="control-label"></label>
                                    <textarea rows="5" asp-for="Komentarz" id="form3Example1cg" class="form-control form-control-lg"></textarea>
                                    <span asp-validation-for="Komentarz" class="text-danger"></span>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <input id="kupAktywo" type="submit" value="Kup aktywo" style="background: var(--color-primary); border: 0; padding: 14px 45px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Portfel/Portfel.App/Views/Portfel/MojePortfele.cshtml
@model IEnumerable<Portfel.Data.Data.Portfel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="about" class="about" style="margin-bottom: 55px;">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h2>Moje portfele</h2>
            <p>
                <a id="dodajPortfel" asp-action="DodajPortfel" style="background: var(--color-primary); border: 0; padding: 8px 25px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;">Dodaj nowy portfel</a>
            </p>
        </div>
        <table class="table align-middle mb-0 bg-white table-striped table-hover">
            <thead class="bg-light">
                <tr>
                    <th>
                        Nazwa
                    </th>
                    <th>
                        Stan konta
                    </th>
                    <th> Akcje</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td id="nazwaPortfela">
                            @Html.DisplayFor(modelItem => item.Nazwa)
                        </td>
                        <td id="stanKonta">
                            @Html.DisplayFor(modelItem => item.KontoGotowkowe.StanKonta)
                        </td>
                        <td>
                            <a id="wplac" asp-action="WplacKwote" asp-controller="Portfel"
                           asp-route-id="@item.Id"
                           style="background: var(--color-primary); border: 0; padding: 2px 12px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;">Wpłać kwotę</a>
                            <a id="wyplac" asp-action="WyplacKwote" asp-controller="Portfel"
                           asp-route-id="@item.Id"
                           style="background: var(--color-primary); border: 0; padding: 2px 12px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;">Wypłać kwotę</a>
                            <a id="kup" asp-action="KupAktywo" asp-controller="Portfel"
                           asp-route-id="@item.Id"
                           style="background: var(--color-primary); border: 0; padding: 2px 12px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;">Kup aktywo</a>
                            <a id="sprzedaj" asp-action="SprzedajAktywo" asp-controller="Portfel"
                           asp-route-id="@item.Id"
                           style="background: var(--color-primary); border: 0; padding: 2px 12px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;">Sprzedaj aktywo</a>
                            <a id="szczegoly" asp-action="SzczegolyPortfela" asp-controller="Portfel"
                           asp-route-id="@item.Id"
                           style="background: var(--color-primary); border: 0; padding: 2px 12px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;">Szczegóły portfela</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

Portfel/Portfel.App/Views/Portfel/SprzedajAktywo.cshtml
@model Portfel.Data.Data.SprzedajAktywoRequest
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="about" class="about" style="margin-bottom: 55px;">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h2>Sprzedaj aktywo</h2>
        </div>
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;  border-color: white;
                                     box-shadow: 0px 2px 25px rgb(0 0 0 / 10%);">
                        <div class="card-body p-5">
                            <div class="info-item d-flex">
                            </div><!-- End Info Item -->
                            <form asp-action="SprzedajAktywo" asp-controller="Portfel">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="PortfelId" />
                                <div class="form mb-4">
                                    <label asp-for="AktywoId">Aktywo</label>
                                    <select asp-for="AktywoId" class="form-control form-control-lg" asp-items="ViewBag.AktywoId"></select>
                                </div>
                                <div class="form mb-4">
                                    <label asp-for="Cena" class="control-label"></label>
                                    <input asp-for="Cena" id="form3Example1cg" class="form-control form-control-lg" />
                                    <span asp-validation-for="Cena" class="text-danger"></span>
                                </div>
                                <div class="form mb-4">
                                    <label asp-for="Ilosc" class="control-label">Ilość</label>
                                    <input asp-for="Ilosc" id="form3Example1cg" class="form-control form-control-lg" />
                                    <span asp-validation-for="Ilosc" class="text-danger"></span>
                                </div>
                                <div class="form mb-4">
                                    <label asp-for="Komentarz" class="control-label"></label>
                                    <textarea rows="5" asp-for="Komentarz" id="form3Example1cg" class="form-control form-control-lg"></textarea>
                                    <span asp-validation-for="Komentarz" class="text-danger"></span>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <input id="sprzedajAktywo" type="submit" value="Sprzedaj aktywo" style="background: var(--color-primary); border: 0; padding: 14px 45px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Portfel/Portfel.App/Views/Portfel/SzczegolyPortfela.cshtml
@model SzczegolyPortfela
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="about" class="about" style="margin-bottom: 55px;">
    <div class="container" data-aos="fade-up">

        <div class="section-header">
            <h2>@Model.NazwaPortfela</h2>
            <p>
                <a asp-action="WszytskieTransakcjeDlaPortfela" asp-controller="Portfel" asp-route-id="@Model.IdPortfela" style="background: var(--color-primary); border: 0; padding: 8px 25px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;">Pokaż wszystkie transakcje</a>
            </p>
        </div>
        <table class="table align-middle mb-0 bg-white table-striped table-hover">
            <thead class="bg-light">
                <tr>
                    <th>
                        <div>Nazwa aktywa</div>
                    </th>
                    <th>
                        <div>Ilość aktywa</div>
                    </th>
                    <th>
                        <div>Średnia cena zakupu</div>
                    </th>
                    <th>
                        <div>Średni koszt pozycji</div>
                    </th>
                    <th>
                        <div>Aktualna wartość pozycji</div>
                    </th>
                    <th>
                        <div>Aktualna cena aktywa</div>
                    </th>
                    <th>Zysk/Strata</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Pozycje)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NazwaAktywa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ilosc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SredniaCenaZakupu)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SredniaWartoscPozycji)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WartoscPozycji)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WartoscAktywa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ZyskStrata) %
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

Portfel/Portfel.App/Views/Portfel/WplacKwote.cshtml
@model Portfel.App.Models.WplataNaPortfelRequest
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="about" class="about" style="margin-bottom: 55px;">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h2>Wpłać kwotę do portfela</h2>
        </div>
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;  border-color: white;
                                     box-shadow: 0px 2px 25px rgb(0 0 0 / 10%);">
                        <div class="card-body p-5">
                            <div class="info-item d-flex">
                            </div>
                            <form asp-action="WplacKwote">
                                <div class="form mb-4">
                                    <label asp-for="Kwota"></label>
                                    <input asp-for="Kwota" id="form3Example1cg" class="form-control form-control-lg" />
                                    <span asp-validation-for="Kwota"></span>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <input type="submit" value="Wpłać kwotę" style="background: var(--color-primary); border: 0; padding: 14px 45px; color: #fff; transition: 0.4s; border-radius: 50px; margin-top: 8px;" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Portfel/Portfel.App/Views/Portfel/WszystkieTransakcje.cshtml
@model WszystkieTransakcjeDlaPortfela
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section id="about" class="about" style="margin-bottom: 55px;">
    <div class="container" data-aos="fade-up">

        <div class="section-header" style="padding-bottom: 0px">
            <h2>@Model.NazwaPortfela</h2>
        </div>
        <div class="section-header" style="padding-bottom: 0px">
            <h5>Zakup/sprzedaż aktyw </h5>
            <h2></h2>
        </div>
        <table class="table align-middle mb-0 bg-white table-striped table-hover">
            <thead class="bg-light">
                <tr>
                    <th>
                        <div>Data dodania</div>
                    </th>
                    <th>
                        <div>Rodzaj transakcji</div>
                    </th>
                    <th>
                        <div>Aktywo</div>
                    </th>
                    <th>
                        <div>Symbol giełdowy</div>
                    </th>
                    <th>
                        <div>Cena</div>
                    </th>
                    <th>
                        <div>Ilość</div>
                    </th>
                    <th>
                        <div>Razem</div>
                    </th>
                    <th>
                        <div>Komentarz</div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Transakcje)
                {
                    <tr>
                        <td>
                            @item.DataTransakcji.ToShortDateString()
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Kierunek)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Aktywo.Nazwa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Aktywo.Symbol)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cena) zł
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ilosc)
                        </td>
                        <td>
                            @{
                                var result = item.Cena * item.Ilosc; // mnożę cenę i ilość
                                <span>@result zł</span>
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Komentarz)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="section-header" style="padding-top: 30px; padding-bottom: 0px">
            <h2></h2>
            <h5>Operacje gotówkowe</h5>
            <h2></h2>
        </div>
        <table class="table align-middle mb-0 bg-white table-striped table-hover">
            <thead class="bg-light">
                <tr>
                    <th>
                        <div>Data dodania</div>
                    </th>
                    <th>
                        <div>Typ operacji</div>
                    </th>
                    <th>
                        <div>Kwota</div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OperacjeGotowkowe)
                {
                    <tr>
                        <td>
                            @item.DataOperacji.ToShortDateString()
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TypOperacjiGotowkowej)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Kwota)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>