Portfel/Portfel.Intranet/Controllers/AktualnoscController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Portfel.Data;
using Portfel.Data.Data;
//using Portfel.Data.Migrations; todo

namespace Portfel.Intranet.Controllers
{
    public class AktualnoscController : Controller
    {
        private readonly PortfelContext _context;

        public AktualnoscController(PortfelContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Aktualnosc.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Pozycja,Tytul,Tresc,FotoUrl, Aktywna")] Aktualnosc aktualnosc)
        {
            if (ModelState.IsValid)
            {
                aktualnosc.DataDodania=DateTime.Now;
                _context.Add(aktualnosc);
 
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aktualnosc);
        }
        // GET: Aktualnosci/Delete/5
        public async Task<IActionResult> UsuwaniePotwierdzone(int id)
        {
            var aktualnosc = await _context.Aktualnosc.FindAsync(id);
          //  _context.Aktualnosc.Remove(aktualnosc);
            aktualnosc.Aktywna = false;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Aktualnosc == null)
            {
                return NotFound();
            }

            var aktualnosc = await _context.Aktualnosc.FindAsync(id);
            if (aktualnosc == null)
            {
                return NotFound();
            }
            return View(aktualnosc);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Pozycja,Tytul,Tresc,FotoUrl,DataDodania, Aktywna")] Aktualnosc aktualnosc)
        {
            if (id != aktualnosc.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aktualnosc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AktualnoscExists(aktualnosc.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aktualnosc);
        }
        private bool AktualnoscExists(int id)
        {
            return _context.Aktualnosc.Any(e => e.Id == id);
        }
     
    }
}

Portfel/Portfel.Intranet/Controllers/AktywoController.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Portfel.Data;
using Portfel.Data.Data;
using Portfel.Data.Serwisy;

namespace Portfel.Intranet.Controllers
{
    public class AktywoController : Controller
    {
        private readonly PortfelContext _context;
        private readonly SymboleSerwis _symboleSerwis;
        private IEnumerable<Aktywo> _aktywa;

        public AktywoController(PortfelContext context, SymboleSerwis symboleSerwis)
        {
            _context = context;
            _symboleSerwis = symboleSerwis;
            
        }

        // GET: SymbolGieldowy
        public async Task<IActionResult> Index()
        {
            return View(await _context.Aktywa.ToListAsync());
        }

        // GET: SymbolGieldowy/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Aktywa == null)
            {
                return NotFound();
            }

            var aktywo = await _context.Aktywa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aktywo == null)
            {
                return NotFound();
            }

            return View(aktywo);
        }

        // GET: SymbolGieldowy/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SymbolGieldowy/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nazwa,Symbol, CenaAktualna")] AktywoViewModel aktywo)
        {
            if (ModelState.IsValid)
            {
                var cena = Convert.ToDecimal(aktywo.CenaAktualna, Thread.CurrentThread.CurrentCulture);
                var noweAktywo = new Aktywo()
                {
                    Aktywna = true,
                    CenaAktualna = cena,
                    Id = aktywo.Id,
                    Nazwa = aktywo.Nazwa,
                    Symbol = aktywo.Symbol
                };
                _context.Add(noweAktywo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aktywo);
        }

        // GET: SymbolGieldowy/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Aktywa == null)
            {
                return NotFound();
            }

            var aktywo = await _context.Aktywa.FindAsync(id);
            if (aktywo == null)
            {
                return NotFound();
            }
            return View(new AktywoViewModel
            {
                Id = aktywo.Id,
                Nazwa = aktywo.Nazwa,
                Symbol = aktywo.Symbol,
                CenaAktualna = aktywo.CenaAktualna.ToString(Thread.CurrentThread.CurrentCulture),
                Aktywna = aktywo.Aktywna
            });
        }

        // POST: SymbolGieldowy/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nazwa,Symbol,CenaAktualna,Aktywna")] AktywoViewModel aktywoViewModel)
        {
            if (id != aktywoViewModel.Id) //todo
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(new Aktywo()
                    {
                        Nazwa = aktywoViewModel.Nazwa,
                        Aktywna = aktywoViewModel.Aktywna,
                        //    CenaAktualna = Convert.ToDecimal(aktywoViewModel.CenaAktualna, ci),
                        CenaAktualna = Convert.ToDecimal(aktywoViewModel.CenaAktualna, Thread.CurrentThread.CurrentCulture),
                        Id = aktywoViewModel.Id,
                        Symbol = aktywoViewModel.Symbol
                    });
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AktywoExists(aktywoViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aktywoViewModel);
        }

        // GET: SymbolGieldowy/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Aktywa == null)
            {
                return NotFound();
            }

            var aktywo = await _context.Aktywa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aktywo == null)
            {
                return NotFound();
            }

            return View(aktywo);
        }

        // POST: SymbolGieldowy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Aktywa == null)
            {
                return Problem("Entity set 'PortfelContext.SymbolGieldowy'  is null.");
            }
            var aktywo = await _context.Aktywa.FindAsync(id);
            if (aktywo != null)
            {
                aktywo.Aktywna = false;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AktywoExists(int id)
        {
            return _context.Aktywa.Any(e => e.Id == id);
        }

        public async Task<IActionResult> AktualizacjaCeny()
        {

            await _symboleSerwis.ZaktualizujCeny();
            return RedirectToAction(nameof(Index));
        }
        public IEnumerable<Aktywo> GetAktywa()
        {
            _aktywa = _context.Aktywa.ToList();
            return _aktywa;
        }

        public Aktywo GetAktywo(int id)
        {
            _aktywa = _context.Aktywa.ToList();
            return _aktywa.FirstOrDefault(p => p.Id == id);
        }

        [HttpPost]
        public Aktywo PostAktywo(string symbol, string nazwa, decimal cenaAktualna)
        {
            var aktywo = new Aktywo()
            {
                Nazwa = nazwa,
                Symbol = symbol,
                CenaAktualna = cenaAktualna,
                Aktywna = true
            };
            _context.Add(aktywo);
            _context.SaveChangesAsync();
            return aktywo;
        }

        [HttpPost]
        public Aktywo PatchAktywo(string symbol, decimal nowaCena)
        {
            var aktywoDoEdycji = _context.Aktywa.Single(aktywo => aktywo.Symbol == symbol);
            aktywoDoEdycji.CenaAktualna = nowaCena;

            var zaktualizowaneAktywo = _context.Update(aktywoDoEdycji);
            _context.SaveChangesAsync();
            return zaktualizowaneAktywo.Entity;
        }
    }
}

Portfel/Portfel.Intranet/Controllers/UzytkownikController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Portfel.Data;
using Portfel.Data.Data;

namespace Portfel.Intranet.Controllers
{
    public class UzytkownikController : Controller
    {
        private readonly PortfelContext _context;

        public UzytkownikController(PortfelContext context)
        {
            _context = context;
        }

        // GET: Uzytkownik
        public async Task<IActionResult> Index()
        {
              return View(await _context.Uzytkownik.ToListAsync());
        }

        // GET: Uzytkownik/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Uzytkownik == null)
            {
                return NotFound();
            }

            var uzytkownik = await _context.Uzytkownik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (uzytkownik == null)
            {
                return NotFound();
            }

            return View(uzytkownik);
        }

        // GET: Uzytkownik/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Uzytkownik/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Imie,Haslo,Email,Aktywna,DataUtworzenia")] Uzytkownik uzytkownik)
        {
            if (ModelState.IsValid)
            {
                uzytkownik.DataUtworzenia = DateTime.Now;
                _context.Add(uzytkownik);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(uzytkownik);
        }

        // GET: Uzytkownik/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Uzytkownik == null)
            {
                return NotFound();
            }

            var uzytkownik = await _context.Uzytkownik.FindAsync(id);
            if (uzytkownik == null)
            {
                return NotFound();
            }
            return View(uzytkownik);
        }

        // POST: Uzytkownik/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Imie,Haslo,Email, Aktywna")] Uzytkownik uzytkownik)
        {
            if (id != uzytkownik.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(uzytkownik);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UzytkownikExists(uzytkownik.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(uzytkownik);
        }

        // GET: Uzytkownik/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Uzytkownik == null)
            {
                return NotFound();
            }

            var uzytkownik = await _context.Uzytkownik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (uzytkownik == null)
            {
                return NotFound();
            }

            return View(uzytkownik);
        }

        // POST: Uzytkownik/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Uzytkownik == null)
            {
                return Problem("Entity set 'PortfelContext.Uzytkownik'  is null.");
            }
            var uzytkownik = await _context.Uzytkownik.FindAsync(id);
            if (uzytkownik != null)
            {
                uzytkownik.Aktywna = false;
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UzytkownikExists(int id)
        {
          return _context.Uzytkownik.Any(e => e.Id == id);
        }
    }
}

Portfel/Portfel.Intranet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfel.Intranet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portfel.Intranet.styles.css" asp-append-version="true" />

    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-icons.css" rel="stylesheet">
    
    <link href="https://unpkg.com/@@uploadcare/blocks@0.17.1/web/file-uploader-regular.min.css"
          rel="stylesheet>"
</head>
<body id="page-top">
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a asp-controller="Home" asp-action="Index" class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-atlas"></i>
                </div>
                <div class="sidebar-brand-text mx-3"> Admin</div>
            </a>
            <div class="sidebar-heading">
                Dane użytkowników
            </div>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Uzytkownik" asp-action="Index">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Uzytkownicy</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="TransakcjaNew" asp-action="Index">
                    <i class="fas fa-fw fa-dollar-sign"></i>
                    <span>Transakcje</span>
                </a>
            </li>
            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Aktualnosc" asp-action="Index">
                    <i class="fas fa-fw fa-newspaper"></i>
                    <span>Aktualnosci</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Definicje</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-area="" asp-controller="Aktywo" asp-action="Index">
                            <span>Aktywa</span>
                        </a>
                    </div>
                </div>
            </li>
            <hr class="sidebar-divider d-none d-md-block">
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright &copy; Your Website 2021</span>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>